---
host: <your ip address>
user: admin
password: <your password>
switches:
- 101
- 102
switch_profile: bon_switch_profile10
interface_type: individual
interface_selector: bon_interface_selector10
interface_policy_group: bon2
interface_ports:
- 1/33
- 1/34
