---
host: 172.31.216.100
user: admin
password: ins3965!
tenant: bon
application:
  name: 3Tier
  optional_args:
    prio: level1
epgs:
- name: Web_EPG
  optional_args:
    bridge_domain: BD1
- name: App_EPG
  optional_args:
    bridge_domain: BD1
- name: DB_EPG
  optional_args:
    bridge_domain: BD1
applied_contracts:
- name: Web_Con
  epg: Web_EPG
  type: provided
- name: App_Con
  epg: App_EPG
  type: provided
- name: DB_Con
  epg: DB_EPG
  type: provided
- name: App_Con
  epg: Web_EPG
  type: consumed
- name: DB_Con
  epg: App_EPG
  type: consumed

