---
host: 198.18.133.200
user: admin
password: C1sco12345
tenant: mgmt
management_address:
  policy_name: switchOob
  optional_args:
    fabric_nodes_id:
    - 101
    - 102
    - 103
    out_of_band_management_epg: default
    out_of_band_gateway: 4.4.4.4/24
    out_of_band_ip_address_from: 4.4.4.30
    out_of_band_ip_address_to: 4.4.4.42
out_of_band_contract:
  contract: oob-default
  optional_args:
    scope: context
    prio: unspecified
out_of_band_epg:
  contract: oob-default
  optional_args:
    prio: unspecified
external_management_entity_instance:
  profile_name: oob-mgmt-ext
  optional_args:
    prio: unspecified
    consumed_contract:
      name: oob-default
      prio: unspecified
    subnet:
      4.4.4.0/24