---
host: 172.31.216.100
user: admin
password: ins3965!
switches:
- 101
- 102
switch_profile: bon_switch_profile1
interface_type: pc
interface_selector: bon_interface_selector1
interface_policy_group: bon_pc_group
interface_ports:
- 1/33
- 1/34
link_level_policy:
  name: bon_llp
  optional_args:
    speed: 1G
cdp_interface_policy:
  name: bon_cdp
  optional_args:
    admin_state: enabled
lldp_interface_policy:
  name: bon_lldp
  optional_args:
    receive_state: disabled
    transmit_state: disabled
lacp_policy:
  name: bon_lacp
  optional_args:
    mode: active
    minimum_number_of_links: 1
    maximum_number_of_links: 16
    control:
    - 'graceful-conv'
    - 'susp-individual'
    - 'fast-sel-hot-stdby'